Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyGlueJob  
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: s3://codepipelinebucket13/script/glue_script.py
      DefaultArguments:
        "--TempDir": "s3://codepipelinebucket13/temp/"
      GlueVersion: "2.0"
      WorkerType: G.1X
      NumberOfWorkers: 3

